apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name | default "app" }}
    type: {{ .Values.labels.type | default "type" }}
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name | default "app" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | default "app" }}
        type: {{ .Values.labels.type | default "type" }}
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - image: "{{ .Values.image.path }}:{{ .Values.image.tag }}"
        name: {{ .Values.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
        ports:
          - name: http-alt
            protocol: TCP
            containerPort: {{ .Values.svc.targetPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.svc.targetPort }}
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.svc.targetPort }}
          initialDelaySeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
