apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name | default "app" }}
    type: {{ .Values.labels.type | default "type" }}
  name: {{ .Values.name | default "app" }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  ports:
  - port: {{ .Values.svc.port }}
    protocol: TCP
    targetPort: {{ .Values.svc.targetPort }}
  selector:
    app: {{ .Values.name}}
  sessionAffinity: None
  type: {{ .Values.svc.type }}
status:
  loadBalancer: {}
