# This workflow will lint and test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-sec-lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

      # https://github.com/securego/gosec#github-action
    - name: Run gosec
      uses: securego/gosec@v2.14.0
      with:
        args: ./...

      # Ref: https://github.com/golangci/golangci-lint-action#how-to-use
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.3.1
      with:
        version: v1.50.1

    - name: Run unit tests
      run: go test -v ./...
